#!/usr/bin/env python3
"""Promote already-generated preview output. Never invokes its root-dependent builder."""
import hashlib, json, re, shutil
from pathlib import Path
from xml.sax.saxutils import escape
from html import escape as html_escape
ROOT = Path(__file__).resolve().parents[1]
PREVIEW = ROOT / 'testi-sivu3'
REPORT = json.loads((PREVIEW / '_build/build-report.json').read_text())
ORIGINAL = json.loads((ROOT / 'scripts/production-article-metadata.json').read_text())
BASE = 'https://aigen.fi'
def route(s): return s.replace('/testi-sivu3/sovellukset/ilmoo/ilmoo-demo-kasittelija.jpg', '/assets/catalog-site/media/ilmoo-demo-kasittelija.jpg').replace('/testi-sivu3/assets/', '/assets/catalog-site/').replace('/testi-sivu3/', '/')
def digest(p): return hashlib.sha256(p.read_bytes()).hexdigest()
protected = {p: digest(p) for p in ROOT.rglob('*') if p.is_file() and (p.relative_to(ROOT).parts[0] in ['testi-sivu','testi-sivu2','testi-sivu3'] or (p.relative_to(ROOT).parts[0]=='assets' and 'catalog-site' not in p.relative_to(ROOT).parts) or p.name in ['CNAME','.nojekyll','google70926c4b93226e56.html'])}
assets = ROOT / 'assets/catalog-site'
# Refuse to overwrite an unrelated asset namespace on first use.
marker = assets / '.promotion-owned'
if assets.exists() and not marker.exists(): raise SystemExit('Asset namespace already exists without ownership marker')
assets.mkdir(parents=True, exist_ok=True)
for p in (PREVIEW / 'assets').rglob('*'):
 if p.is_file():
  dst=assets/p.relative_to(PREVIEW/'assets'); dst.parent.mkdir(parents=True,exist_ok=True)
  if p.suffix in ['.js','.css']: dst.write_text(route(p.read_text()))
  else: shutil.copyfile(p,dst)
(assets/'media').mkdir(exist_ok=True)
shutil.copyfile(PREVIEW/'sovellukset/ilmoo/ilmoo-demo-kasittelija.jpg', assets/'media/ilmoo-demo-kasittelija.jpg')
marker.write_text('Generated by scripts/promote-catalog.py\n')
org={'@context':'https://schema.org','@type':'Organization','@id':BASE+'/#organization','name':'AI Generation Oy','url':BASE+'/','email':'contact@aigen.fi'}
for key, langs in REPORT['pages'].items():
 for lang, oldurl in langs.items():
  url=route(oldurl); src=ROOT/REPORT['written'][oldurl]; html=route(src.read_text())
  html=re.sub(r'\n  <div class="preview-strip">.*?</div>\s*</div>\n','\n',html,flags=re.S)
  html=html.replace('noindex,nofollow','index,follow')
  html=re.sub(r'(<title>.*?)\s*\|\s*(?:Esikatselu 3|Preview 3)(</title>)',r'\1\2',html)
  html=re.sub(r'\s*[–—-]\s*(?:Esikatselu 3|Preview 3)(?=</title>)', '', html)
  alternates='\n'.join(f'  <link rel="alternate" hreflang="{lng}" href="{BASE+route(u)}">' for lng,u in langs.items())
  metadata=f'  <link rel="canonical" href="{BASE+url}">\n{alternates}\n  <link rel="alternate" hreflang="x-default" href="{BASE+route(langs["fi"])}">'
  schema=[org,{'@context':'https://schema.org','@type':'WebSite','@id':BASE+'/#website','name':'Aigen','url':BASE+'/','inLanguage':['fi','en'],'publisher':{'@id':BASE+'/#organization'}}]
  post=REPORT.get('posts',{}).get(key+':'+lang)
  if post:
   original=ORIGINAL.get(post['src'],{})
   title=re.search(r'<h1[^>]*>(.*?)</h1>',html,re.S).group(1)
   schema.append({'@context':'https://schema.org','@type':'BlogPosting','headline':re.sub('<[^>]+>','',title),'url':BASE+url,'mainEntityOfPage':BASE+url,'datePublished':original.get('datePublished',post['published']),'dateModified':original.get('dateModified',post['modified']),'inLanguage':lang,'publisher':{'@id':BASE+'/#organization'}})
  if post:
   for field in ['author','image','description','copyrightHolder','copyrightYear']:
    if field in original: schema[-1][field]=original[field]
   if 'image' not in schema[-1] and post.get('image',{}).get('src'): schema[-1]['image']=BASE+route(post['image']['src'])
  else:
   source=REPORT.get('live_sources',{}).get(key,{}).get(lang)
   if source in ORIGINAL:
    article=dict(ORIGINAL[source]);article.update(url=BASE+url,mainEntityOfPage=BASE+url,inLanguage=lang);schema.append(article)
  title=html_escape(re.search(r'<title>(.*?)</title>',html,re.S).group(1),quote=True)
  description=re.search(r'<meta name="description" content="([^"]*)">',html).group(1)
  metadata+=f'\n  <meta property="og:title" content="{title}">\n  <meta property="og:description" content="{description}">\n  <meta property="og:url" content="{BASE+url}">\n  <meta property="og:type" content="{"article" if post else "website"}">'
  if post and post.get('image',{}).get('src'): metadata+=f'\n  <meta property="og:image" content="{BASE+route(post["image"]["src"])}">'
  metadata+='\n  <script type="application/ld+json">'+json.dumps(schema,ensure_ascii=False).replace('</','<\\/')+'</script>'
  if key=='home':
   mapping={'contact':'/yritys/#yhteys','services':'/raataloity-kehitys/','about':'/yritys/','products':'/sovellukset/','tools':'/sovellukset/','other-products':'/sovellukset/'} if lang=='fi' else {'contact':'/en/company/#contact','services':'/en/custom-development/','about':'/en/company/','products':'/en/apps/','tools':'/en/apps/','other-products':'/en/apps/'}
   metadata+='\n  <script>(function(){var m='+json.dumps(mapping)+';function go(){var h=location.hash.slice(1);if(m[h])location.replace(m[h].split("#")[0]+location.search+(m[h].includes("#")?"#"+m[h].split("#")[1]:""));}go();window.addEventListener("hashchange",go);})();</script>'
  html=html.replace('</head>',metadata+'\n</head>')
  dst=ROOT/url.lstrip('/')/'index.html'; dst.parent.mkdir(parents=True,exist_ok=True); dst.write_text(html)
for oldurl,target in REPORT['aliases'].items():
 html=route((PREVIEW/oldurl.removeprefix('/testi-sivu3/')/'index.html').read_text())
 html=html.replace('Aigen preview','Aigen').replace('noindex,nofollow','noindex,follow')
 html=re.sub(r'var m = (.*?), h =', lambda m: 'var m = '+json.dumps(dict(json.loads(m.group(1)), **{'main':'sisalto','main-nav':'paavalikko'}))+', h =', html)
 html=re.sub(r'(<meta http-equiv="refresh"[^>]+>)',r'<noscript>\1</noscript>',html)
 html=html.replace('</head>',f'  <link rel="canonical" href="{BASE+route(target)}">\n</head>')
 dst=ROOT/route(oldurl).lstrip('/')/'index.html'; dst.parent.mkdir(parents=True,exist_ok=True); dst.write_text(html)
urls=sorted(route(u) for langs in REPORT['pages'].values() for u in langs.values())
xml='<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'+''.join(f'  <url><loc>{escape(BASE+u)}</loc></url>\n' for u in urls)+'</urlset>\n'
(ROOT/'sitemap.xml').write_text(xml)
(ROOT/'robots.txt').write_text('User-agent: *\nAllow: /\nDisallow: /testi-sivu/\nDisallow: /testi-sivu2/\nDisallow: /testi-sivu3/\nDisallow: /blog/artikkeli-pohja/\nDisallow: /scripts/\nDisallow: /docs/\nDisallow: /tests/\n\nSitemap: https://aigen.fi/sitemap.xml\n')
assert all(digest(p)==h for p,h in protected.items()), 'Protected file changed'
print(f'Promoted {len(urls)} canonical pages, {len(REPORT["aliases"])} aliases; protected files unchanged.')
